x-php: &php
  build: 
    context: .
    dockerfile: ./.docker/php/Dockerfile
  working_dir: /var/www/html
  restart: always
  expose:
    - "9000"
  depends_on:
    pgsql:
      condition: service_healthy

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "10"

services:
  # PostGres Service
  pgsql:
    container_name: PgSQL
    image: "postgres:13-alpine"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "test"
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  php:
    <<: [*php, *logging]
    command: ["php-fpm", "-y", "/usr/local/etc/php-fpm.conf", "-R"]

  queue:
    <<: [*php, *logging]
    command: php artisan queue:work

  scheduler:
    <<: [*php, *logging]
    command: php artisan schedule:work

  # Nginx Service
  nginx:
    build: ./.docker/nginx
    container_name: Nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./:/var/www/html:ro
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - php
